//go:generate go run gen.go
// +build ignore
package main

import (
	"os"
	"os/exec"
	"text/template"
	"time"
	"strings"
)

func main() {

	cmd := exec.Command("git", "describe", "--always", "--tag")
	version, err := cmd.Output()
	die(err)

	f, err := os.Create("version.go")
	die(err)
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		Version   string
	}{
		Timestamp: time.Now(),
		Version: strings.TrimSpace(string(version)),
	})
}

func die(err error) {
	if err != nil {
		panic(err.Error())
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated at {{ .Timestamp }}
package version

const Version = "UBW-{{.Version}}"
`))
